# Generated by Django 2.2.13 on 2020-10-22 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment_log',
        ),
    ]
