# Generated by Django 2.2.13 on 2020-10-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_log',
            name='transaction_status',
            field=models.CharField(max_length=10),
        ),
    ]
