# Generated by Django 2.2.13 on 2020-10-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20201022_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_log',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
