# Generated by Django 2.2.13 on 2020-10-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20201022_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_log',
            name='transaction_reference',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
