# Generated by Django 2.2.13 on 2020-10-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_payment_log_transaction_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_log',
            name='transaction_reference',
            field=models.IntegerField(),
        ),
    ]
