# Generated by Django 2.2.13 on 2020-10-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('category', models.CharField(choices=[('Formal-Wear', 'Formal-Wear'), ('Casual-Wear', 'Casual-Wear'), ('Accessories', 'Accessories'), ('Ties', 'Ties')], default='Formal-Wear', max_length=15)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=255)),
                ('stock_qty', models.IntegerField()),
            ],
        ),
    ]
