# Generated by Django 2.2.13 on 2020-10-18 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EW_user_admin', '0002_auto_20201018_0141'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
