# Generated by Django 2.2.13 on 2020-10-18 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EW_user_admin', '0003_auto_20201018_0206'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
