# Generated by Django 2.2.13 on 2020-10-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EW_user_admin', '0004_auto_20201018_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
