# Generated by Django 2.2.13 on 2020-10-19 03:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_console', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
