# Generated by Django 2.2.13 on 2020-10-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_console', '0002_product_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Business-Wear', 'Business-Wear'), ('Casual-Wear', 'Casual-Wear'), ('Footwear', 'Footwear'), ('Accessories', 'Accessories')], default='Business-Wear', max_length=15),
        ),
    ]
